package presentation.order;

import bll.OrderBLL;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;

/**
 * Main order window class generated by the Swing form editor
 * Contains ActionListeners for each button in the window
 *
 * @author Csabi
 */
public class AddOrderWindow extends JFrame {
    private JPanel addOrderPanel;
    private JTextField quantityField;
    private JButton addOrderButton;
    private JTextField productIdField;
    private JTextField clientIdField;
    private JButton viewOrdersButton;
    private JTextField orderIdField;
    private JButton deleteOrderButton;

    public AddOrderWindow() {
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(HIDE_ON_CLOSE);
        frame.setResizable(true);
        frame.add(addOrderPanel);
        frame.setSize(300, 300);
        //frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);

        addOrderButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    OrderBLL.getInstance().insertOrder(
                            Integer.parseInt(orderIdField.getText()),
                            Integer.parseInt(clientIdField.getText()),
                            Integer.parseInt(productIdField.getText()),
                            Integer.parseInt(quantityField.getText()));
                } catch (SQLException ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Missing or invalid input");
                }
                orderIdField.setText(null);
                productIdField.setText(null);
                clientIdField.setText(null);
                quantityField.setText(null);
            }
        });
        viewOrdersButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    new ShowOrdersWindow();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        });
        deleteOrderButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new DeleteOrderWindow();
            }
        });
    }
}
